<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">NPDI</h5>
        <p class="grey-text text-lighten-4">Núcleo de Processamento Digital de Imagens.
                                        <br>Departamento de Ciência da Computação.
                                        <br>Instituto de Ciências Exatas.
                                        <br>Universidade Federal de Minas Gerais.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Contato</h5>
        <ul>
          <li class="grey-text text-lighten-3"><strong>Endereço:</strong> <a target="_blank" class="grey-text text-lighten-3" href="https://www.google.com.br/maps/place/Av.+Pres.+Ant%C3%B4nio+Carlos,+6627+-+Lagoinha,+Belo+Horizonte+-+MG/@-19.8670171,-43.9636391,17z/data=!3m1!4b1!4m5!3m4!1s0xa69063d33adf9d:0xc47b2d3a7dcf4bf2!8m2!3d-19.8670222!4d-43.9614504">
                    Av. Antônio Carlos 6627 - ICEx - sl. 3055
                <br>Pampulha - CEP 31270-010
                <br>Belo Horizonte - Minas Gerais - Brasil.</a></li>
          <li class="grey-text text-lighten-3"><strong>Telefone:</strong> (31) 3409-5854</li>
          <li class="grey-text text-lighten-3"><strong>Informações:</strong> npdi@listas.dcc.ufmg.br</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>
</body>
</html>
